 platform :ios, '7.0' # (or whatever version you want to target)

 pod 'Brightcove-Player-SDK', '~> 4.1.6'

# Remove 64-bit build architecture from Pods targets
post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['ARCHS'] = '$(ARCHS_STANDARD_32_BIT)'
    end
  end
end